apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traffic-report.fullname" . }}-config
  labels:
    {{- include "traffic-report.labels" . | nindent 4 }}
type: Opaque
data:
  yolo-endpoint: {{ .Values.app.yolo.endpoint | b64enc | quote }}
  yolo-api-key: {{ .Values.app.yolo.apiKey | b64enc | quote }}
  qwen-endpoint: {{ .Values.app.qwen.endpoint | b64enc | quote }}
  qwen-api-key: {{ .Values.app.qwen.apiKey | b64enc | quote }}