{{- if .Values.ezua.virtualService.enabled }}
# ServiceEntry for external model endpoints
# Note: This is a generic template - users will configure actual endpoints via Streamlit UI
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "traffic-report.fullname" . }}-external-models
  labels:
    {{- include "traffic-report.labels" . | nindent 4 }}
spec:
  hosts:
  # Allow all external HTTPS traffic for model endpoints
  # Users will configure specific endpoints via Streamlit UI
  - "*.ingress.*"
  - "*.com"
  - "*.net"
  - "*.org"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "traffic-report.fullname" . }}-external-tls
  labels:
    {{- include "traffic-report.labels" . | nindent 4 }}
spec:
  host: "*.ingress.*"
  trafficPolicy:
    tls:
      mode: SIMPLE
{{- end }}