apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic-report.fullname" . }}
  labels:
    {{- include "traffic-report.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "traffic-report.selectorLabels" . | nindent 4 }}